-- V1 Initial DB schema for Junie
-- Create beers table
CREATE TABLE IF NOT EXISTS beers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT NULL,
    name VARCHAR(255) NOT NULL,
    style VARCHAR(255) NOT NULL,
    upc VARCHAR(255) NOT NULL,
    quantity_on_hand INT NULL,
    price DECIMAL(19,2) NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP NULL,
    CONSTRAINT uq_beers_upc UNIQUE (upc)
);

-- Create beer_orders table
CREATE TABLE IF NOT EXISTS beer_orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT NULL,
    customer_ref VARCHAR(255) NOT NULL,
    payment_amount DECIMAL(19,2) NULL,
    status VARCHAR(64) NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NULL
);

-- Index for beer_orders customer_ref
CREATE INDEX IF NOT EXISTS idx_beer_orders_customer_ref ON beer_orders(customer_ref);

-- Create beer_order_lines table with composite PK
CREATE TABLE IF NOT EXISTS beer_order_lines (
    beer_order_id INT NOT NULL,
    beer_id INT NOT NULL,
    version INT NULL,
    order_quantity INT NOT NULL,
    status VARCHAR(64) NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NULL,
    CONSTRAINT pk_beer_order_lines PRIMARY KEY (beer_order_id, beer_id),
    CONSTRAINT fk_bol_order FOREIGN KEY (beer_order_id) REFERENCES beer_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_bol_beer FOREIGN KEY (beer_id) REFERENCES beers(id)
);

-- Indexes to support lookups on FKs
CREATE INDEX IF NOT EXISTS idx_bol_order ON beer_order_lines(beer_order_id);
CREATE INDEX IF NOT EXISTS idx_bol_beer ON beer_order_lines(beer_id);
