-- V2 Add customers table and relation to beer_orders

-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    phone VARCHAR(64) NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(64) NOT NULL,
    postal_code VARCHAR(64) NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NULL
);

-- Indexes on customers
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);

-- Add customer_id to beer_orders if not exists
ALTER TABLE beer_orders ADD COLUMN IF NOT EXISTS customer_id INT NULL;

-- Index for beer_orders customer_id
CREATE INDEX IF NOT EXISTS idx_beer_orders_customer_id ON beer_orders(customer_id);

-- Add FK constraint
ALTER TABLE beer_orders
    ADD CONSTRAINT fk_beer_orders_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id)
    ON DELETE RESTRICT;
